import { AriaNode, AriaEdge, ContainerCanvas } from '../../shared/types';

function isC4Node(node: AriaNode): boolean {
  return node.type === 'c4-container' || node.type === 'c4-component';
}

function filterEdgesByNodeIds(edges: AriaEdge[], nodeIds: Set<string>): AriaEdge[] {
  return edges.filter((edge) => nodeIds.has(edge.source) && nodeIds.has(edge.target));
}

// C4 Context レベルの Mermaid 記法を生成する（MVP は一方向出力のみ）
export function generateArchitectureMermaid(
  nodes: AriaNode[],
  edges: AriaEdge[],
  containerCanvases: Record<string, ContainerCanvas> = {}
): string {
  const contextNodes = nodes.filter(isC4Node);
  const contextNodeIds = new Set(contextNodes.map((node) => node.id));
  const contextEdges = filterEdgesByNodeIds(edges, contextNodeIds);
  const styledContainerNodeIds = new Set<string>();
  const styledComponentNodeIds = new Set<string>();

  for (const node of contextNodes) {
    if (node.type === 'c4-container') styledContainerNodeIds.add(node.id);
    if (node.type === 'c4-component') styledComponentNodeIds.add(node.id);
  }

  const lines: string[] = [
    '<!-- AUTO-GENERATED by ARIA — DO NOT EDIT MANUALLY -->',
    'graph TD',
  ];

  lines.push('');
  lines.push('  %% Context Layer');
  lines.push('  subgraph context_layer["Context Layer"]');

  // ノードを出力する
  for (const node of contextNodes) {
    const label = escapeMermaidText(node.data.label);
    const desc = node.data.description
      ? `\\n${escapeMermaidText(node.data.description)}`
      : '';
    lines.push(`    ${node.id}["${label}${desc}"]`);
  }

  // エッジを出力する
  for (const edge of contextEdges) {
    const label = edge.label ? ` |${escapeMermaidText(edge.label)}|` : '';
    lines.push(`    ${edge.source} -->${label} ${edge.target}`);
  }

  if (contextNodes.length === 0) {
    lines.push('    %% ノードがありません');
  }
  lines.push('  end');

  // M9: コンテナドリルダウン用のキャンバスも同一ファイルに追記する（サブグラフとして表現）
  const rootNodeLabelById = new Map(contextNodes.map((n) => [n.id, n.data.label]));
  for (const [containerId, canvas] of Object.entries(containerCanvases)) {
    const innerNodes = canvas.nodes.filter(isC4Node);
    const innerNodeIds = new Set(innerNodes.map((node) => node.id));
    const innerEdges = filterEdgesByNodeIds(canvas.edges, innerNodeIds);

    for (const node of innerNodes) {
      if (node.type === 'c4-container') styledContainerNodeIds.add(node.id);
      if (node.type === 'c4-component') styledComponentNodeIds.add(node.id);
    }

    lines.push('');
    lines.push(`  %% Container Layer (${escapeMermaidText(String(containerId))})`);
    const subgraphId = `container_${containerId.replace(/[^A-Za-z0-9_]/g, '_')}`;
    const parentLabel = rootNodeLabelById.get(containerId) ?? canvas.nodeId ?? containerId;
    lines.push(
      `  subgraph ${subgraphId}["Container Layer: ${escapeMermaidText(parentLabel)} (${escapeMermaidText(containerId)})"]`
    );

    if (innerNodes.length === 0) {
      lines.push('    %% コンテナ内ノードがありません');
    } else {
      for (const node of innerNodes) {
        const label = escapeMermaidText(node.data.label);
        const desc = node.data.description
          ? `\\n${escapeMermaidText(node.data.description)}`
          : '';
        lines.push(`    ${node.id}["${label}${desc}"]`);
      }

      for (const edge of innerEdges) {
        const label = edge.label ? ` |${escapeMermaidText(edge.label)}|` : '';
        lines.push(`    ${edge.source} -->${label} ${edge.target}`);
      }
    }

    lines.push('  end');
  }

  lines.push('');
  lines.push('  %% C4 Node Styles');
  lines.push('  classDef c4Container fill:#1f2d3d,stroke:#4ea1ff,color:#d4d4d4,stroke-width:1.2px;');
  lines.push('  classDef c4Component fill:#1f3b33,stroke:#4ec9b0,color:#d4d4d4,stroke-width:1.2px;');
  if (styledContainerNodeIds.size > 0) {
    lines.push(`  class ${Array.from(styledContainerNodeIds).join(',')} c4Container;`);
  }
  if (styledComponentNodeIds.size > 0) {
    lines.push(`  class ${Array.from(styledComponentNodeIds).join(',')} c4Component;`);
  }

  return lines.join('\n') + '\n';
}

function escapeMermaidText(value: string): string {
  return value.replace(/"/g, "'");
}
