import * as path from 'path';
import * as fs from 'fs/promises';
import * as vscode from 'vscode';
import { tExt } from '../i18n';

// .cursorrules の内容（英語・ネガティブフレーミング）
const CURSORRULES_CONTENT = `# ARIA Project Rules for AI Assistants
# Auto-generated by ARIA VS Code Extension — DO NOT DELETE THIS FILE

## CRITICAL: .ai-context/ Directory Rules

### status.md — TASK BOARD
- NEVER remove task ID anchors: <!-- task-id-task-XXXXXXXX -->
  Removing anchors causes tasks to be duplicated in Inbox.
- NEVER modify section headers: ## 📥 Inbox, ## 📋 Todo, ## 🔄 In Progress, ## ✅ Done
  Modifying headers breaks the parser.
- NEVER reorder sections.
- You MAY change [ ] to [x] to mark tasks as done (reverse sync will update the GUI).
- You MAY change task titles (text after the checkbox).
- You MAY add new tasks at the END of any section WITHOUT an ID anchor.
  New tasks without IDs will be auto-assigned to Inbox for human review.

### aria-state.json — MASTER STATE
- DO NOT manually edit this file unless you know exactly what you are doing.
- DO NOT change task IDs (format: "task-xxxxxxxx").
- DO NOT add fields that do not exist in the schema.
- Valid status values ONLY: "Todo", "In Progress", "Done", "Inbox"
- Invalid status values will be reset to "Inbox" automatically.

### architecture.mermaid — SYSTEM DIAGRAM
- This file is READ-ONLY for AI agents.
- It is auto-generated from the ARIA GUI canvas.
- DO NOT modify this file. Changes will be overwritten on next GUI action.

### adr/ — ARCHITECTURE DECISION RECORDS
- You MAY edit the "Decision" and "Rejected Options" sections.
- DO NOT change the ID field or the file naming convention (ADR-XXXXXXXX-slug.md, derived from ADR ID).

## Development Philosophy
- Quality over Speed: do not make assumptions, ask the human developer.
- Single Source of Truth: aria-state.json is the master. Markdown files are the communication interface.
- When in doubt, add a task to status.md (Inbox section) rather than making changes directly.
`;

/**
 * プロジェクトルートに .cursorrules を生成する。
 * 既存ファイルがある場合は上書きしない。
 */
export async function generateCursorRulesIfNotExists(
  workspacePath: string
): Promise<void> {
  const filePath = path.join(workspacePath, '.cursorrules');

  try {
    await fs.access(filePath);
    // ファイルが存在する場合は何もしない
  } catch {
    // ファイルが存在しない場合のみ生成する
    try {
      await fs.writeFile(filePath, CURSORRULES_CONTENT, { encoding: 'utf-8' });
      vscode.window.showInformationMessage(
        tExt('ext.generator.cursorrules_created'),
      );
    } catch (err) {
      // 書き込み失敗は無視する（致命的ではない）
      console.error('ARIA: .cursorrules の生成に失敗しました', err);
    }
  }
}
