import { KanbanTask, TaskStatus } from '../../shared/types';

// AI による破壊的編集を事前に抑制するガードヘッダー（英語・ネガティブフレーミング）
const GUARD_HEADER = `<!-- ============================================================
  DO NOT EDIT THIS FILE MANUALLY.
  This file is AUTO-GENERATED by ARIA. Any manual edits will be overwritten.
  You MAY toggle checkbox/title in this file for reverse sync.
  (ARIA will normalize and sync back to aria-state.json.)
  Task IDs (HTML comments) are machine-readable anchors — do not remove them.
============================================================ -->

`;

const STATUS_ORDER: TaskStatus[] = ['Inbox', 'Todo', 'In Progress', 'Done'];

const STATUS_HEADERS: Record<TaskStatus, string> = {
  Inbox: '## 📥 Inbox（未分類・AI生成タスク）',
  Todo: '## 📋 Todo',
  'In Progress': '## 🔄 In Progress',
  Done: '## ✅ Done',
};

export function generateStatusMd(tasks: Record<string, KanbanTask>): string {
  const taskList = Object.values(tasks);
  const sections: string[] = [GUARD_HEADER];

  sections.push('# ARIA — Status\n');

  for (const status of STATUS_ORDER) {
    const filtered = taskList.filter((t) => t.status === status);
    sections.push(STATUS_HEADERS[status]);

    if (filtered.length === 0) {
      sections.push('_（なし）_\n');
    } else {
      for (const task of filtered) {
        // Done ステータスは [x]、それ以外は [ ] で出力する（逆同期のキー）
        const checkbox = task.status === 'Done' ? '[x]' : '[ ]';

        let dateStr = '';
        if (task.startDate || task.dueDate) {
          if (task.startDate && task.dueDate) dateStr = ` 📅 ${task.startDate}〜${task.dueDate}`;
          else if (task.startDate) dateStr = ` 📅 ${task.startDate}〜`;
          else if (task.dueDate) dateStr = ` 📅 〜${task.dueDate}`;
        }

        // IDアンカーをタスク行末に付与する（逆同期のキー）
        sections.push(`- ${checkbox} ${task.title}${dateStr} <!-- task-id-${task.id} -->`);
      }
      sections.push('');
    }
  }

  return sections.join('\n');
}
